# https://www.akshare.xyz/data/stock/stock.htm

In [2]:
import akshare as ak

### 实时行情数据 https://www.akshare.xyz/data/stock/stock.html#id9

In [11]:
df = ak.stock_zh_a_spot_em()

In [15]:
df.head()

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,...,量比,换手率,市盈率-动态,市净率,总市值,流通市值,涨速,5分钟涨跌,60日涨跌幅,年初至今涨跌幅
0,1,301199,迈赫股份,24.88,20.02,4.15,23608.0,5.817299e+07,20.02,24.88,...,1.95,7.08,-131.48,1.93,3.317499e+09,8.294992e+08,0.0,0.00,-15.58,-29.06
1,2,300479,神思电子,20.71,19.99,3.45,408511.0,8.133550e+08,18.77,20.71,...,3.39,20.73,-217.46,5.43,4.080716e+09,4.080716e+09,0.0,0.00,-19.42,28.08
2,3,300660,江苏雷利,34.10,19.99,5.68,284077.0,9.592513e+08,10.52,34.10,...,4.19,22.63,31.88,3.27,8.843028e+09,4.279949e+09,0.0,0.00,62.77,18.20
3,4,300064,金刚退,1.45,19.83,0.24,224918.0,3.059139e+07,17.36,1.45,...,1.11,3.23,-3.95,-1.89,1.747941e+09,1.009533e+09,0.0,0.00,-34.39,-18.08
4,5,300024,机器人,10.58,16.91,1.53,1256035.0,1.322360e+09,17.13,10.86,...,7.56,8.33,-70.25,3.99,1.640124e+10,1.594553e+10,0.0,-0.09,13.64,-5.28

In [14]:
df.columns

Index(['序号', '代码', '名称', '最新价', '涨跌幅', '涨跌额', '成交量', '成交额', '振幅', '最高', '最低',
       '今开', '昨收', '量比', '换手率', '市盈率-动态', '市净率', '总市值', '流通市值', '涨速', '5分钟涨跌',
       '60日涨跌幅', '年初至今涨跌幅'],
      dtype='object')

In [3]:
# period='daily'; choice of {'daily', 'weekly', 'monthly'} # adjust ''  'qfq'  'hfq'
df = ak.stock_zh_a_hist(symbol='603636', period='daily', start_date='20100301', end_date='20220628', adjust='qfq')

In [7]:
df.tail(30)

,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
1718,2022-05-17,10.56,10.69,10.78,10.32,324923,346866576.0,4.36,1.23,0.13,5.50
1719,2022-05-18,10.93,10.57,11.02,10.27,415736,446204736.0,7.02,-1.12,-0.12,7.04
1720,2022-05-19,10.18,10.45,10.55,10.14,227186,238420750.0,3.88,-1.14,-0.12,3.85
1721,2022-05-20,10.45,10.39,10.57,10.34,182197,191434145.0,2.20,-0.57,-0.06,3.08
1722,2022-05-23,10.33,10.34,10.56,10.30,217122,227588412.0,2.50,-0.48,-0.05,3.68
1723,2022-05-24,10.38,9.62,10.41,9.60,273260,275279696.0,7.83,-6.96,-0.72,4.63
1724,2022-05-25,9.66,10.10,10.19,9.66,242273,244449333.0,5.51,4.99,0.48,4.10
1725,2022-05-26,10.09,10.00,10.16,9.82,167570,168352525.0,3.37,-0.99,-0.10,2.84
1726,2022-05-27,10.12,10.20,10.38,9.93,291313,297598448.0,4.50,2.00,0.20,4.93
1727,2022-05-30,10.17,10.07,10.22,9.90,209825,212585028.0,3.14,-1.27,-0.13,3.55
1728,2022-05-31,10.09,10.08,10.16,9.91,146249,148261162.0,2.48,0.10,0.01,2.48
1729,2022-06-01,10.10,10.13,10.27,9.97,150729,153967233.0,2.98,0.50,0.05,2.55
1730,2022-06-02,10.26,10.10,10.26,9.98,123529,125504175.0,2.76,-0.30,-0.03,2.09
1731,2022-06-06,10.04,11.12,11.12,10.04,424692,460233952.0,10.69,10.10,1.02,7.19
1732,2022-06-07,11.40,11.22,11.70,11.12,769674,882796944.0,5.22,0.90,0.10,13.03
1733,2022-06-08,11.22,11.40,11.70,10.94,527918,602715152.0,6.77,1.60,0.18,8.94
1734,2022-06-09,11.22,11.12,11.47,10.87,409019,457598320.0,5.26,-2.46,-0.28,6.92
1735,2022-06-10,11.16,11.27,11.42,11.11,298223,338353472.0,2.79,1.35,0.15,5.05
1736,2022-06-13,11.18,11.72,12.05,11.13,464838,544294608.0,8.16,3.99,0.45,7.87
1737,2022-06-14,11.56,11.47,11.63,11.07,288532,328938784.0,4.78,-2.13,-0.25,4.88
1738,2022-06-15,11.44,11.49,11.64,11.25,256802,297113888.0,3.40,0.17,0.02,4.35
1739,2022-06-16,11.49,11.70,12.05,11.45,295126,346778816.0,5.22,1.83,0.21,5.00
1740,2022-06-17,11.70,12.39,12.72,11.69,465790,570533872.0,8.80,5.90,0.69,7.88
1741,2022-06-20,12.43,12.20,12.43,11.82,314833,381902336.0,4.92,-1.53,-0.19,5.33
1742,2022-06-21,12.18,12.22,12.68,12.03,268561,331390000.0,5.33,0.16,0.02,4.55
1743,2022-06-22,12.12,13.06,13.39,11.89,507611,646147328.0,12.27,6.87,0.84,8.59
1744,2022-06-23,13.00,13.70,13.75,12.70,444469,588171824.0,8.04,4.90,0.64,7.52
1745,2022-06-24,14.20,13.18,14.30,13.07,533538,733590704.0,8.98,-3.80,-0.52,9.03
1746,2022-06-27,12.99,13.10,13.49,12.85,315162,414179168.0,4.86,-0.61,-0.08,5.33
1747,2022-06-28,13.23,12.80,13.26,12.76,271738,352005808.0,3.82,-2.29,-0.30,4.60

### 股票指数 https://www.akshare.xyz/data/stock/stock.html#id39

In [16]:
df = ak.stock_zh_index_spot()

In [18]:
df.head()

,代码,名称,最新价,涨跌额,涨跌幅,昨收,今开,最高,最低,成交量,成交额
0,sh000001,上证指数,3409.2103,30.025,0.889,3379.1852,3377.6793,3412.1017,3358.8666,412056516,525512509335
1,sh000002,Ａ股指数,3573.0437,31.521,0.890,3541.5223,3539.9322,3576.1032,3520.1718,411618448,525037995756
2,sh000003,Ｂ股指数,309.9019,2.146,0.697,307.7560,307.7754,309.9019,307.2753,377707,207751510
3,sh000004,工业指数,3217.7625,34.362,1.079,3183.4001,3183.1709,3220.0560,3163.0560,256610732,388059949809
4,sh000005,商业指数,2737.6820,18.053,0.664,2719.6292,2714.8480,2742.8684,2696.3003,27761518,28211626080

In [12]:
df = ak.stock_zh_index_daily(symbol="sh000001")

In [14]:
df.tail()

            date      open      high       low     close       volume
7695  2022-06-21  3313.787  3329.390  3279.827  3306.719  39445689100
7696  2022-06-22  3309.118  3311.021  3266.543  3267.202  37552978200
7697  2022-06-23  3269.055  3320.149  3262.294  3320.149  40061421100
7698  2022-06-24  3324.736  3356.715  3322.950  3349.747  39081973400
7699  2022-06-27  3364.003  3393.309  3364.003  3379.185  41411773800

In [25]:
df = ak.stock_jgdy_tj_em(date="20220619")

In [26]:
df

,序号,代码,名称,最新价,涨跌幅,接待机构数量,接待方式,接待人员,接待地点,接待日期,公告日期
0,1,300813,泰林生物,41.47,-1.26,5,特定对象调研,"董事会秘书、财务总监 叶星月,证券事务代表 叶军君","浙江省杭州市滨江区南环路2930号,浙江泰林生物技术股份有限公司12F会议室",2022-06-21,2022-06-21
1,2,002050,三花智控,24.30,-2.80,5,"特定对象调研,现场参观",厉轩,杭州,2022-06-20,2022-06-21
2,3,600572,康恩贝,4.50,-0.88,2,"现场调研,线上交流","副总裁、董事会秘书 金祖成,总裁顾问 杨俊德,投资者关系管理高级经理 汪鸯",None,2022-06-20,2022-06-21
3,4,000753,漳州发展,3.80,-2.31,1,业绩说明会,"董事长 赖小强,董事、总经理 陈毅建,董事、副总经理、董事会秘书 林惠娟",网络形式(全景网“投资者关系互动平台”http://ir.p5w.net),2022-06-20,2022-06-21
4,5,603887,城地香江,7.84,0.64,1,"业绩说明会,网络文字互动","董事长、公司总裁 谢晓东,董事、公司副总裁、财务总监 王琦,董事会秘书 裘爽,独立董事 刘华",上海证券交易所-上证路演中心,2022-06-20,2022-06-21
5,6,002955,鸿合科技,22.85,1.83,5,特定对象调研,"副总经理、董事会秘书 夏亮,投资者关系主管 刘宇彤",融新科技中心F座12层,2022-06-20,2022-06-20
6,7,002402,和而泰,17.50,-2.67,3,"电话会议,通讯","高级副总裁、董事会秘书、财经中心总经理 罗珊珊,证券事务代表 艾雯",公司会议室,2022-06-20,2022-06-20

In [20]:
df.columns

Index(['序号', '代码', '名称', '最新价', '涨跌幅', '接待机构数量', '接待方式', '接待人员', '接待地点',
       '接待日期', '公告日期'],
      dtype='object')

In [28]:
df = ak.stock_jgdy_detail_em(date="20220620")

In [29]:
df

,序号,代码,名称,最新价,涨跌幅,调研机构,机构类型,调研人员,接待方式,接待人员,接待地点,调研日期,公告日期
0,1,300813,泰林生物,41.47,-1.26,广发证券,证券公司,"孙怡璇,赵浩东",特定对象调研,"董事会秘书、财务总监 叶星月,证券事务代表 叶军君","浙江省杭州市滨江区南环路2930号,浙江泰林生物技术股份有限公司12F会议室",2022-06-21,2022-06-21
1,2,300813,泰林生物,41.47,-1.26,财通证券,证券公司,谢铭,特定对象调研,"董事会秘书、财务总监 叶星月,证券事务代表 叶军君","浙江省杭州市滨江区南环路2930号,浙江泰林生物技术股份有限公司12F会议室",2022-06-21,2022-06-21
2,3,300813,泰林生物,41.47,-1.26,南方基金,基金管理公司,蔡强,特定对象调研,"董事会秘书、财务总监 叶星月,证券事务代表 叶军君","浙江省杭州市滨江区南环路2930号,浙江泰林生物技术股份有限公司12F会议室",2022-06-21,2022-06-21
3,4,300813,泰林生物,41.47,-1.26,景顺长城基金,基金管理公司,"姜雪婷,Yin Zhang",特定对象调研,"董事会秘书、财务总监 叶星月,证券事务代表 叶军君","浙江省杭州市滨江区南环路2930号,浙江泰林生物技术股份有限公司12F会议室",2022-06-21,2022-06-21
4,5,300813,泰林生物,41.47,-1.26,德邦证券,证券公司,"陈铁林,王绍玲",特定对象调研,"董事会秘书、财务总监 叶星月,证券事务代表 叶军君","浙江省杭州市滨江区南环路2930号,浙江泰林生物技术股份有限公司12F会议室",2022-06-21,2022-06-21

In [30]:
df = ak.stock_account_statistics_em()

In [32]:
df.head()

,数据日期,新增投资者-数量,新增投资者-环比,新增投资者-同比,期末投资者-总量,期末投资者-A股账户,期末投资者-B股账户,沪深总市值,沪深户均市值,上证指数-收盘,上证指数-涨跌幅
0,2022-05,120.26,-0.0430,-0.1484,20490.87,20430.86,239.28,780858.070194,38.2195,3186.4271,4.5737
1,2022-04,125.67,-0.4541,-0.2570,20370.61,20310.56,239.31,738998.967219,36.3850,3047.0624,-6.3077
2,2022-03,230.20,0.6273,-0.0708,20244.94,20184.86,239.33,805106.854669,39.8867,3252.2029,-6.0683
3,2022-02,141.46,0.0682,-0.1210,20014.73,19954.60,239.35,864560.067024,43.3264,3462.3064,3.0007
4,2022-01,132.43,-0.0360,-0.3677,19873.28,19813.10,239.35,838634.003679,42.3272,3361.4397,-7.6471

In [35]:
df = ak.stock_yjbb_em(date="20220331") # 年报季报-业绩报表

In [37]:
df.head()

,序号,股票代码,股票简称,每股收益,营业收入-营业收入,营业收入-同比增长,营业收入-季度环比增长,净利润-净利润,净利润-同比增长,净利润-季度环比增长,每股净资产,净资产收益率,每股经营现金流量,销售毛利率,所处行业,最新公告日期
0,1,873083,博菱电器,0.020,3.459598e+08,NaN,-29.2925,6.681214e+06,NaN,-68.8533,1.745188,1.05,0.060539,16.042225,None,2022-06-21 00:00:00
1,2,688053,思科瑞,0.250,5.069338e+07,22.058318,NaN,1.887821e+07,4.270000,NaN,4.489272,5.77,-0.064816,70.287862,电子元件,2022-06-21 00:00:00
2,3,400097,刚泰1,-0.079,1.284582e+07,-92.449878,-16.3296,-1.181335e+08,-19.830000,78.8534,-1.277882,-6.41,-0.002360,10.170682,None,2022-06-21 00:00:00
3,4,839559,振有电子,0.060,1.075715e+08,0.176797,NaN,6.006421e+06,-55.264506,NaN,2.841008,1.99,0.111870,17.293547,None,2022-06-20 00:00:00
4,5,838810,春光药装,0.110,3.992703e+07,37.914308,-43.0470,5.770197e+06,11.780000,-60.4803,1.960126,5.57,0.186486,38.161444,None,2022-06-20 00:00:00

In [40]:
df = ak.stock_yjkb_em(date="20220331")

In [41]:
df.head()

,序号,股票代码,股票简称,每股收益,营业收入-营业收入,营业收入-去年同期,营业收入-同比增长,营业收入-季度环比增长,净利润-净利润,净利润-去年同期,净利润-同比增长,净利润-季度环比增长,每股净资产,净资产收益率,所处行业,公告日期,市场板块,证券类型
0,1,301289,国缆检测,NaN,5.272230e+07,5.573556e+07,-5.406344,-399.044618,16766900.0,1.964402e+07,-14.646274,-420.335375,NaN,NaN,专业服务,2022-06-21 00:00:00,深交所创业板,A股
1,2,837821,则成电子,NaN,6.551710e+07,4.618463e+07,41.859087,-340.567122,2420500.0,7.060448e+06,-65.717471,-449.184471,NaN,NaN,None,2022-06-20 00:00:00,北京证券交易所,A股
2,3,688349,三一重能,NaN,2.048414e+09,2.110985e+09,-2.964073,NaN,596745600.0,4.805363e+08,24.183254,NaN,NaN,NaN,风电设备,2022-06-17 00:00:00,上交所科创板,A股
3,4,301139,元道通信,NaN,4.065797e+08,2.531613e+08,60.601062,-282.201111,19488100.0,1.474901e+07,32.131568,-277.976442,NaN,NaN,通信设备,2022-06-08 00:00:00,深交所创业板,A股
4,5,833874,泰祥股份,NaN,3.726450e+07,4.498416e+07,-17.160833,-459.938288,13485300.0,1.613345e+07,-16.414029,-656.579542,NaN,NaN,None,2022-05-17 00:00:00,北京证券交易所,A股

In [45]:
df = ak.stock_yjyg_em(date="20220630") # 业绩预告

In [46]:
df.head()

,序号,股票代码,股票简称,预测指标,业绩变动,预测数值,业绩变动幅度,业绩变动原因,预告类型,上年同期值,公告日期
0,1,688349,三一重能,归属于上市公司股东的净利润,"预计2022年1-6月归属于上市公司股东的净利润盈利:84,600万元至103,300万元,...",9.395000e+08,12.765,None,略增,8.332007e+08,2022-06-21 00:00:00
1,2,688349,三一重能,营业收入,"预计2022年1-6月营业收入:384,700万元至470,200万元,同比上年变动:-2....",4.274500e+09,8.290,None,续盈,3.947597e+09,2022-06-21 00:00:00
2,3,688349,三一重能,扣除非经常性损益后的净利润,"预计2022年1-6月扣除非经常性损益后的净利润盈利:84,700万元至103,600万元,...",9.415000e+08,16.900,None,略增,8.054216e+08,2022-06-21 00:00:00
3,4,688297,中无人机,归属于上市公司股东的净利润,"预计2022年1-6月归属于上市公司股东的净利润盈利:19,000万元至22,000万元,同...",2.050000e+08,-8.725,"公司预计2022年1-6月实现归属于母公司所有者的净利润较去年同期降低,主要是不同合同之间的...",略减,NaN,2022-06-21 00:00:00
4,5,688297,中无人机,扣除非经常性损益后的净利润,"预计2022年1-6月扣除非经常性损益后的净利润盈利:19,000万元至22,000万元,同...",2.050000e+08,-8.670,"公司预计2022年1-6月实现归属于母公司所有者的净利润较去年同期降低,主要是不同合同之间的...",略减,NaN,2022-06-21 00:00:00

In [48]:
df = ak.stock_lrb_em(date="20220331")

In [49]:
df.head()

,序号,股票代码,股票简称,净利润,净利润同比,营业总收入,营业总收入同比,营业总支出-营业支出,营业总支出-销售费用,营业总支出-管理费用,营业总支出-财务费用,营业总支出-营业总支出,营业利润,利润总额,公告日期
0,1,688053,思科瑞,1.887821e+07,4.270000,5.069338e+07,22.058318,1.506209e+07,2633919.25,5775338.84,456438.39,2.958761e+07,2.113455e+07,2.162774e+07,2022-06-21
1,2,688322,奥比中光,-6.090941e+07,-38.701567,8.259601e+07,24.337745,4.436260e+07,11797291.66,32275661.92,-3370586.37,1.724346e+08,-7.564013e+07,-7.564886e+07,2022-06-20
2,3,000506,中润资源,2.643174e+08,980.180000,6.321042e+07,-40.878682,7.456146e+07,348546.74,24333079.25,11781032.92,1.134685e+08,2.489593e+08,2.557932e+08,2022-06-17
3,4,002433,太安堂,-3.735361e+07,36.890000,1.912530e+08,-75.351382,1.224711e+08,27117040.51,47939524.30,29381700.72,2.403716e+08,-4.110214e+07,-4.155838e+07,2022-06-16
4,5,688400,凌云光,-1.464539e+07,45.248883,5.255194e+08,25.998272,3.587781e+08,64415096.39,50120543.14,1518080.77,5.585749e+08,-2.228422e+07,-2.214610e+07,2022-06-15

In [50]:
df = ak.stock_xjll_em(date="20220331")

In [51]:
df.head()

,序号,股票代码,股票简称,净现金流-净现金流,净现金流-同比增长,经营性现金流-现金流量净额,经营性现金流-净现金流占比,投资性现金流-现金流量净额,投资性现金流-净现金流占比,融资性现金流-现金流量净额,融资性现金流-净现金流占比,公告日期
0,1,688053,思科瑞,-1.759069e+07,33.132971,-4861162.89,-27.634864,-1.442779e+07,-82.019496,1698268.42,9.654360,2022-06-21
1,2,688322,奥比中光,-2.293249e+07,81.815288,30443678.95,132.753494,-4.450046e+07,-194.049850,-8053394.81,-35.117842,2022-06-20
2,3,000506,中润资源,9.493547e+07,403.470607,-41248590.43,-43.449082,1.995864e+08,210.233740,-63361401.84,-66.741547,2022-06-17
3,4,002433,太安堂,-2.109535e+07,52.268533,13460157.43,63.806279,-8.271468e+05,-3.920991,-33730652.58,-159.896157,2022-06-16
4,5,688400,凌云光,-1.388699e+08,-16.873525,-66923689.77,-48.191632,-6.783704e+07,-48.849336,-3520351.80,-2.534999,2022-06-15

In [52]:
df = ak.stock_ggcg_em() # 股东增减持

In [56]:
df.head()

,代码,名称,最新价,涨跌幅,股东名称,持股变动信息-增减,持股变动信息-变动数量,持股变动信息-占总股本比例,持股变动信息-占流通股比例,变动后持股情况-持股总数,变动后持股情况-占总股本比例,变动后持股情况-持流通股数,变动后持股情况-占流通股比例,变动开始日,变动截止日,公告日
0,601236,红塔证券,9.94,-2.36,云南省投资控股集团有限公司,减持,3301.7000,0.699989,1.29,81723.8839,17.33,81723.8839,31.94,2022-03-22,2022-06-21,2022-06-22
1,600143,金发科技,9.15,-2.03,广发原驰·金发科技1号定向资产管理计划,减持,7076.6436,2.749682,2.75,0.0000,NaN,0.0000,NaN,NaT,2022-06-21,2022-06-21
2,688687,凯因科技,18.01,-1.26,天津君睿祺股权投资合伙企业(有限合伙),减持,266.7300,1.570585,2.32,582.4000,3.43,582.4000,5.06,2022-03-19,2022-06-20,2022-06-22
3,688659,元琛科技,9.63,-0.41,南海成长精选(天津)股权投资基金合伙企业(有限合伙),减持,94.0000,0.587500,1.09,1675.6077,10.47,1675.6077,19.36,2022-06-07,2022-06-20,2022-06-21
4,688639,华恒生物,129.00,0.00,嘉兴市兴和股权投资合伙企业(有限合伙),减持,103.4367,0.954213,1.50,438.5595,4.05,438.5595,6.37,2022-06-07,2022-06-20,2022-06-22

### 资金流向 https://www.akshare.xyz/data/stock/stock.html#id137

In [57]:
df = ak.stock_fund_flow_individual(symbol="即时") # {“即时”, "3日排行", "5日排行", "10日排行", "20日排行"}

100%|██████████████████████████████████████████████████████████████████████████████████| 95/95 [00:27<00:00,  3.46it/s]

In [68]:
df.head()

,序号,股票代码,股票简称,最新价,涨跌幅,换手率,流入资金,流出资金,净额,成交额
0,1,1323,慕思股份,56.06,44.00%,3.12%,0.00,6866.81万,-6866.81万,6936.29万
1,2,300912,凯龙高科,20.10,20.00%,13.30%,4364.69万,1.08亿,-6433.01万,1.61亿
2,3,301302,华如科技,61.70,18.59%,28.05%,2.02亿,2.21亿,-1897.46万,4.38亿
3,4,300852,四会富仕,38.10,14.00%,11.84%,6092.27万,4561.67万,1530.60万,1.12亿
4,5,300817,双飞股份,15.90,13.82%,13.62%,2365.75万,8566.04万,-6200.29万,1.13亿

### 基本面数据 https://www.akshare.xyz/data/stock/stock.html#id148

In [19]:
df = ak.stock_zh_a_gdhs(symbol="20210930") # 股东户数

In [21]:
df.head()

,代码,名称,最新价,涨跌幅,股东户数-本次,股东户数-上次,股东户数-增减,股东户数-增减比例,区间涨跌幅,股东户数统计截止日-本次,股东户数统计截止日-上次,户均持股市值,户均持股数量,总市值,总股本,公告日期
0,688981,中芯国际,46.06,1.90,352391,347706,4685,1.347403,-10.708509,2021-09-30,2021-06-30,3.036490e+05,5500.886799,1.070032e+11,1.938463e+09,2021-11-12
1,000419,通程控股,4.98,1.63,21827,22376,-549,-2.453522,1.247074,2021-09-30,2021-06-30,1.080840e+05,24904.139598,2.359149e+09,5.435827e+08,2021-11-10
2,688621,阳光诺和,105.90,-1.20,5924,6023,-99,-1.643699,26.136835,2021-09-30,2021-09-17,2.464821e+06,13504.388926,1.460160e+10,8.000000e+07,2021-11-06
3,688663,新风光,35.11,1.77,6871,9421,-2550,-27.067190,35.033445,2021-09-30,2021-07-09,6.578933e+05,20368.214234,4.520385e+09,1.399500e+08,2021-11-03
4,603668,天马科技,19.97,4.55,23496,26124,-2628,-10.059715,8.321775,2021-09-30,2021-06-30,1.450278e+05,18569.500170,3.407573e+09,4.363090e+08,2021-11-02

In [22]:
df = ak.stock_zh_a_gdhs_detail_em(symbol="603636") # 股东户数详情

In [26]:
df.head()

,股东户数统计截止日,区间涨跌幅,股东户数-本次,股东户数-上次,股东户数-增减,股东户数-增减比例,户均持股市值,户均持股数量,总市值,总股本,股本变动,股本变动原因,股东户数公告日期,代码,名称
0,2022-03-31,70.693512,70950,28513,42437,148.833865,127068.498947,8326.900324,9.015510e+09,590793578,0,None,2022-04-28,603636,南威软件
1,2021-12-31,6.682578,28513,29538,-1025,-3.470106,185238.122517,20720.147933,5.281695e+09,590793578,0,None,2022-04-28,603636,南威软件
2,2021-09-30,-11.835277,29538,29421,117,0.397675,167609.526157,20001.136773,4.950850e+09,590793578,0,None,2021-10-30,603636,南威软件
3,2021-06-30,-0.925926,29421,30918,-1497,-4.841840,193376.912958,20080.676320,5.689342e+09,590793578,0,None,2021-08-26,603636,南威软件
4,2021-03-31,4.516129,30918,33480,-2562,-7.652330,185733.669001,19108.402161,5.742514e+09,590793578,0,None,2021-04-28,603636,南威软件

In [27]:
df = ak.stock_circulate_stock_holder(stock="603636") # 流通股东

In [31]:
df.head()

0        截止日期        公告日期 编号          股东名称    持股数量(股) 占流通股比例(%)   股本性质
0  2022-03-31  2022-04-28  1           吴志雄  239181429    40.485   自然人股
1  2022-03-31  2022-04-28  2   中电科投资控股有限公司   29897679     5.061    国有股
2  2022-03-31  2022-04-28  3  上海云鑫创业投资有限公司   29897678     5.061  境内法人股
3  2022-03-31  2022-04-28  4           刘志强   21240622     3.595   自然人股
4  2022-03-31  2022-04-28  5           刘妍婧    6408080     1.085   自然人股

In [32]:
df = ak.stock_sector_spot(indicator="地域") #  {"新浪行业", "启明星行业", "概念", "地域", "行业"}

In [36]:
df.head()

,label,板块,公司家数,平均价格,涨跌额,涨跌幅,总成交量,总成交额,股票代码,个股-涨跌幅,个股-当前价,个股-涨跌额,股票名称
0,diyu_650000,新疆维吾尔自治区,56,11.965179,0.157679,1.335410,1357689343,15320194686,sz300859,19.986,33.62,5.60,西域旅游
1,diyu_640000,宁夏回族自治区,16,8.630000,0.103750,1.216830,342838274,2482171840,sz000962,6.322,11.10,0.66,东方钽业
2,diyu_630000,青海省,11,12.971818,0.220909,1.732497,408276278,8571848689,sh600869,6.024,5.28,0.30,远东股份
3,diyu_620000,甘肃省,36,9.358611,0.080000,0.862198,1045303196,8918333872,sz002219,4.861,3.02,0.14,*ST恒康
4,diyu_610000,陕西省,69,31.337681,0.251594,0.809347,1454782477,23330807520,sz000561,10.066,8.31,0.76,烽火电子

##### https://www.akshare.xyz/data/stock/stock.html#id217  A股个股指标

In [59]:
df = ak.stock_a_lg_indicator(symbol="603636")

In [61]:
df.head()

,trade_date,pe,pe_ttm,pb,ps,ps_ttm,dv_ratio,dv_ttm,total_mv
0,2022-06-28,55.8161,64.7849,2.9697,4.406,4.4226,0.9209,1.5733,756215.7798
1,2022-06-27,57.1243,66.3033,3.0393,4.5093,4.5263,0.8999,1.5373,773939.5872
2,2022-06-24,57.4731,66.7082,3.0579,4.5368,4.5539,0.8944,1.5279,778665.9358
3,2022-06-23,59.7407,69.3401,3.1785,4.7158,4.7336,0.8604,1.4699,809387.2019
4,2022-06-22,56.9499,66.1009,3.0301,4.4955,4.5125,0.9026,1.542,771576.4129

##### https://www.akshare.xyz/data/stock/stock.html#id218  A 股等权重与中位数市盈率

In [62]:
df = ak.stock_a_ttm_lyr()

In [64]:
df.tail()

,date,middlePETTM,averagePETTM,middlePELYR,averagePELYR,quantileInAllHistoryMiddlePeTtm,quantileInRecent10YearsMiddlePeTtm,quantileInAllHistoryAveragePeTtm,quantileInRecent10YearsAveragePeTtm,quantileInAllHistoryMiddlePeLyr,quantileInRecent10YearsMiddlePeLyr,quantileInAllHistoryAveragePeLyr,quantileInRecent10YearsAveragePeLyr,close
4237,2022-06-21,31.93,47.10,31.99,47.61,0.27183,0.24526,0.30462,0.28153,0.21000,0.15787,0.16258,0.13273,4325.57
4238,2022-06-22,31.29,46.48,31.55,47.03,0.23756,0.20313,0.27790,0.24639,0.18802,0.13309,0.15074,0.12649,4270.62
4239,2022-06-23,32.00,47.43,32.14,48.13,0.27524,0.24959,0.31722,0.29984,0.21698,0.16639,0.18231,0.15445,4343.88
4240,2022-06-26,32.50,48.03,32.38,48.28,0.29828,0.28059,0.33506,0.32633,0.22896,0.18171,0.18628,0.15863,4394.77
4241,2022-06-27,32.71,48.39,32.57,48.65,0.30976,0.29666,0.35054,0.34858,0.23503,0.18871,0.19613,0.16976,4444.26

##### https://www.akshare.xyz/data/stock/stock.html#id219 A 股等权重与中位数市净率

In [65]:
df = ak.stock_a_all_pb()

In [67]:
df.tail()

,date,middlePB,equalWeightAveragePB,close,quantileInAllHistoryMiddlePB,quantileInRecent10YearsMiddlePB,quantileInAllHistoryEqualWeightAveragePB,quantileInRecent10YearsEqualWeightAveragePB
4240,2022-06-21,2.57,3.59,3306.72,0.36359,0.37850,0.40698,0.40692
4241,2022-06-22,2.53,3.54,3267.20,0.34017,0.34335,0.38496,0.37505
4242,2022-06-23,2.58,3.62,3320.15,0.36931,0.38724,0.41834,0.42305
4243,2022-06-24,2.61,3.66,3349.75,0.38596,0.41135,0.43143,0.44179
4244,2022-06-27,2.64,3.71,3379.19,0.39906,0.42775,0.44664,0.46480

##### https://www.akshare.xyz/data/stock/stock.html#id220  A 股市盈率和市净率

In [72]:
df = ak.stock_a_pe_and_pb(symbol='000300.SH')

In [73]:
df

,date,addTtmPe,middleAddTtmPe,addLyrPe,middleAddLyrPe,addPb,averageTtmPe,averageLyr,averagePb,middleAveragePb,close
0,2005-04-08,14.98,20.65,15.68,21.17,2.01,30.39,33.19,2.12,1.92,1003.45
1,2005-04-11,15.12,20.65,15.76,21.40,2.03,29.77,33.43,2.14,1.95,995.42
2,2005-04-12,14.75,20.30,15.21,20.85,1.99,29.03,32.45,2.09,1.88,978.70
3,2005-04-13,15.12,20.78,15.59,21.45,2.04,29.53,32.99,2.15,1.95,1000.90
4,2005-04-14,14.99,20.56,15.42,21.14,2.02,28.95,32.23,2.11,1.93,986.98
...,...,...,...,...,...,...,...,...,...,...,...
4181,2022-06-22,11.08,21.06,11.33,21.32,1.35,31.95,30.95,4.20,2.54,4270.62
4182,2022-06-23,11.25,21.42,11.50,21.84,1.37,32.58,31.54,4.27,2.63,4343.88
4183,2022-06-24,11.33,21.38,11.58,21.79,1.38,32.97,31.92,4.31,2.71,4394.77
4184,2022-06-27,11.44,21.85,11.70,21.63,1.40,33.28,32.30,4.38,2.73,4444.26
4185,2022-06-28,11.53,21.82,11.79,21.97,1.41,33.63,32.63,4.43,2.77,4490.52

### 大宗交易 https://www.akshare.xyz/data/stock/stock.html#id252

In [74]:
df = ak.stock_zh_a_alerts_cls()

In [83]:
df.head()

           时间                                               快讯信息
0  2022-06-28  【快讯：券商股异动 第一创业涨停】财联社6月28日电，第一创业直线拉升涨停，华西证券、国信证...
1  2022-06-28  【快讯：PCB概念股震荡走强 博敏电子涨停】财联社6月28日电，博敏电子涨停，世运电路、天津...
2  2022-06-28  【快讯：深成指涨逾1%】财联社6月28日电，指数走强，深成指拉升涨逾1.00%，沪指涨0.6...
3  2022-06-28  【快讯：三大指数全线翻红 上证指数站上3400点】财联社6月28日电，上证指数涨0.61%，...
4  2022-06-28  【快讯：酒店、旅游股异动拉升 华天酒店涨停】财联社6月28日电，华天酒店涨停，众信旅游、西域...

In [78]:
df = ak.stock_news_em(stock="603636")

In [79]:
list(df['url'])

['http://finance.eastmoney.com/a/202206212419290926.html',
 'http://finance.eastmoney.com/a/202206212418665395.html',
 'http://finance.eastmoney.com/a/202206202418626978.html',
 'http://finance.eastmoney.com/a/202206202418604253.html',
 'http://finance.eastmoney.com/a/202206202418543898.html',
 'http://finance.eastmoney.com/a/202206172416997593.html',
 'http://finance.eastmoney.com/a/202206082405777639.html',
 'http://stock.eastmoney.com/a/202206062402687617.html',
 'http://stock.eastmoney.com/a/202206062402459998.html',
 'http://finance.eastmoney.com/a/202206022401183643.html',
 'http://finance.eastmoney.com/a/202205182383863555.html',
 'http://finance.eastmoney.com/a/202205092372911347.html',
 'http://finance.eastmoney.com/a/202204282363931226.html',
 'http://finance.eastmoney.com/a/202204282363918472.html',
 'http://finance.eastmoney.com/a/202204282363909971.html',
 'http://finance.eastmoney.com/a/202204192348678694.html',
 'http://finance.eastmoney.com/a/202204102337510828.html',
 'http://finance.eastmoney.com/a/202204102337487813.html',
 'http://finance.eastmoney.com/a/202204102337487045.html',
 'http://stock.eastmoney.com/a/202204012331436373.html']

In [9]:
df = ak.stock_financial_report_sina(stock="603636", symbol="现金流量表")

In [10]:
df.columns

Index(['报表日期', '单位', '一、经营活动产生的现金流量', '销售商品、提供劳务收到的现金', '收到的税费返还',
       '收到的其他与经营活动有关的现金', '经营活动现金流入小计', '购买商品、接受劳务支付的现金', '支付给职工以及为职工支付的现金',
       '支付的各项税费', '支付的其他与经营活动有关的现金', '经营活动现金流出小计', '经营活动产生的现金流量净额',
       '二、投资活动产生的现金流量', '收回投资所收到的现金', '取得投资收益所收到的现金',
       '处置固定资产、无形资产和其他长期资产所收回的现金净额', '处置子公司及其他营业单位收到的现金净额', '收到的其他与投资活动有关的现金',
       '投资活动现金流入小计', '购建固定资产、无形资产和其他长期资产所支付的现金', '投资所支付的现金',
       '取得子公司及其他营业单位支付的现金净额', '支付的其他与投资活动有关的现金', '投资活动现金流出小计', '投资活动产生的现金流量净额',
       '三、筹资活动产生的现金流量', '吸收投资收到的现金', '其中：子公司吸收少数股东投资收到的现金', '取得借款收到的现金',
       '发行债券收到的现金', '收到其他与筹资活动有关的现金', '筹资活动现金流入小计', '偿还债务支付的现金',
       '分配股利、利润或偿付利息所支付的现金', '其中：子公司支付给少数股东的股利、利润', '支付其他与筹资活动有关的现金',
       '筹资活动现金流出小计', '筹资活动产生的现金流量净额', '四、汇率变动对现金及现金等价物的影响', '五、现金及现金等价物净增加额',
       '加:期初现金及现金等价物余额', '六、期末现金及现金等价物余额', '附注', '净利润', '少数股东权益', '未确认的投资损失',
       '资产减值准备', '固定资产折旧、油气资产折耗、生产性物资折旧', '无形资产摊销', '长期待摊费用摊销', '待摊费用的减少',
       '预提费用的增加', '处置固定资产、无形资产和其他长期资产的损失', '固定资产报废损失', '公允价值变动损失',
       '递延收益增加（减：减少）', '预计负债', '财务费用', '投资损失', '递延所得税资产减少', '递延所得税负债增加',
       '存货的减少', '经营性应收项目的减少', '经营性应付项目的增加', '已完工尚未结算款的减少(减:增加)',
       '已结算尚未完工款的增加(减:减少)', '其他', '经营活动产生现金流量净额', '债务转为资本', '一年内到期的可转换公司债券',
       '融资租入固定资产', '现金的期末余额', '现金的期初余额', '现金等价物的期末余额', '现金等价物的期初余额',
       '现金及现金等价物的净增加额'],
      dtype='object')

In [2]:
df = ak.stock_balance_sheet_by_report_em(symbol="SH603636")

In [8]:
list(df.columns)

['SECUCODE',
 'SECURITY_CODE',
 'SECURITY_NAME_ABBR',
 'ORG_CODE',
 'ORG_TYPE',
 'REPORT_DATE',
 'REPORT_TYPE',
 'REPORT_DATE_NAME',
 'SECURITY_TYPE_CODE',
 'NOTICE_DATE',
 'UPDATE_DATE',
 'CURRENCY',
 'ACCEPT_DEPOSIT_INTERBANK',
 'ACCOUNTS_PAYABLE',
 'ACCOUNTS_RECE',
 'ACCRUED_EXPENSE',
 'ADVANCE_RECEIVABLES',
 'AGENT_TRADE_SECURITY',
 'AGENT_UNDERWRITE_SECURITY',
 'AMORTIZE_COST_FINASSET',
 'AMORTIZE_COST_FINLIAB',
 'AMORTIZE_COST_NCFINASSET',
 'AMORTIZE_COST_NCFINLIAB',
 'APPOINT_FVTPL_FINASSET',
 'APPOINT_FVTPL_FINLIAB',
 'ASSET_BALANCE',
 'ASSET_OTHER',
 'ASSIGN_CASH_DIVIDEND',
 'AVAILABLE_SALE_FINASSET',
 'BOND_PAYABLE',
 'BORROW_FUND',
 'BUY_RESALE_FINASSET',
 'CAPITAL_RESERVE',
 'CIP',
 'CONSUMPTIVE_BIOLOGICAL_ASSET',
 'CONTRACT_ASSET',
 'CONTRACT_LIAB',
 'CONVERT_DIFF',
 'CREDITOR_INVEST',
 'CURRENT_ASSET_BALANCE',
 'CURRENT_ASSET_OTHER',
 'CURRENT_LIAB_BALANCE',
 'CURRENT_LIAB_OTHER',
 'DEFER_INCOME',
 'DEFER_INCOME_1YEAR',
 'DEFER_TAX_ASSET',
 'DEFER_TAX_LIAB',
 'DERIVE_FINASSET',
 'DERIVE_FINLIAB',
 'DEVELOP_EXPENSE',
 'DIV_HOLDSALE_ASSET',
 'DIV_HOLDSALE_LIAB',
 'DIVIDEND_PAYABLE',
 'DIVIDEND_RECE',
 'EQUITY_BALANCE',
 'EQUITY_OTHER',
 'EXPORT_REFUND_RECE',
 'FEE_COMMISSION_PAYABLE',
 'FIN_FUND',
 'FINANCE_RECE',
 'FIXED_ASSET',
 'FIXED_ASSET_DISPOSAL',
 'FVTOCI_FINASSET',
 'FVTOCI_NCFINASSET',
 'FVTPL_FINASSET',
 'FVTPL_FINLIAB',
 'GENERAL_RISK_RESERVE',
 'GOODWILL',
 'HOLD_MATURITY_INVEST',
 'HOLDSALE_ASSET',
 'HOLDSALE_LIAB',
 'INSURANCE_CONTRACT_RESERVE',
 'INTANGIBLE_ASSET',
 'INTEREST_PAYABLE',
 'INTEREST_RECE',
 'INTERNAL_PAYABLE',
 'INTERNAL_RECE',
 'INVENTORY',
 'INVEST_REALESTATE',
 'LEASE_LIAB',
 'LEND_FUND',
 'LIAB_BALANCE',
 'LIAB_EQUITY_BALANCE',
 'LIAB_EQUITY_OTHER',
 'LIAB_OTHER',
 'LOAN_ADVANCE',
 'LOAN_PBC',
 'LONG_EQUITY_INVEST',
 'LONG_LOAN',
 'LONG_PAYABLE',
 'LONG_PREPAID_EXPENSE',
 'LONG_RECE',
 'LONG_STAFFSALARY_PAYABLE',
 'MINORITY_EQUITY',
 'MONETARYFUNDS',
 'NONCURRENT_ASSET_1YEAR',
 'NONCURRENT_ASSET_BALANCE',
 'NONCURRENT_ASSET_OTHER',
 'NONCURRENT_LIAB_1YEAR',
 'NONCURRENT_LIAB_BALANCE',
 'NONCURRENT_LIAB_OTHER',
 'NOTE_ACCOUNTS_PAYABLE',
 'NOTE_ACCOUNTS_RECE',
 'NOTE_PAYABLE',
 'NOTE_RECE',
 'OIL_GAS_ASSET',
 'OTHER_COMPRE_INCOME',
 'OTHER_CREDITOR_INVEST',
 'OTHER_CURRENT_ASSET',
 'OTHER_CURRENT_LIAB',
 'OTHER_EQUITY_INVEST',
 'OTHER_EQUITY_OTHER',
 'OTHER_EQUITY_TOOL',
 'OTHER_NONCURRENT_ASSET',
 'OTHER_NONCURRENT_FINASSET',
 'OTHER_NONCURRENT_LIAB',
 'OTHER_PAYABLE',
 'OTHER_RECE',
 'PARENT_EQUITY_BALANCE',
 'PARENT_EQUITY_OTHER',
 'PERPETUAL_BOND',
 'PERPETUAL_BOND_PAYBALE',
 'PREDICT_CURRENT_LIAB',
 'PREDICT_LIAB',
 'PREFERRED_SHARES',
 'PREFERRED_SHARES_PAYBALE',
 'PREMIUM_RECE',
 'PREPAYMENT',
 'PRODUCTIVE_BIOLOGY_ASSET',
 'PROJECT_MATERIAL',
 'RC_RESERVE_RECE',
 'REINSURE_PAYABLE',
 'REINSURE_RECE',
 'SELL_REPO_FINASSET',
 'SETTLE_EXCESS_RESERVE',
 'SHARE_CAPITAL',
 'SHORT_BOND_PAYABLE',
 'SHORT_FIN_PAYABLE',
 'SHORT_LOAN',
 'SPECIAL_PAYABLE',
 'SPECIAL_RESERVE',
 'STAFF_SALARY_PAYABLE',
 'SUBSIDY_RECE',
 'SURPLUS_RESERVE',
 'TAX_PAYABLE',
 'TOTAL_ASSETS',
 'TOTAL_CURRENT_ASSETS',
 'TOTAL_CURRENT_LIAB',
 'TOTAL_EQUITY',
 'TOTAL_LIAB_EQUITY',
 'TOTAL_LIABILITIES',
 'TOTAL_NONCURRENT_ASSETS',
 'TOTAL_NONCURRENT_LIAB',
 'TOTAL_OTHER_PAYABLE',
 'TOTAL_OTHER_RECE',
 'TOTAL_PARENT_EQUITY',
 'TRADE_FINASSET',
 'TRADE_FINASSET_NOTFVTPL',
 'TRADE_FINLIAB',
 'TRADE_FINLIAB_NOTFVTPL',
 'TREASURY_SHARES',
 'UNASSIGN_RPOFIT',
 'UNCONFIRM_INVEST_LOSS',
 'USERIGHT_ASSET',
 'ACCEPT_DEPOSIT_INTERBANK_YOY',
 'ACCOUNTS_PAYABLE_YOY',
 'ACCOUNTS_RECE_YOY',
 'ACCRUED_EXPENSE_YOY',
 'ADVANCE_RECEIVABLES_YOY',
 'AGENT_TRADE_SECURITY_YOY',
 'AGENT_UNDERWRITE_SECURITY_YOY',
 'AMORTIZE_COST_FINASSET_YOY',
 'AMORTIZE_COST_FINLIAB_YOY',
 'AMORTIZE_COST_NCFINASSET_YOY',
 'AMORTIZE_COST_NCFINLIAB_YOY',
 'APPOINT_FVTPL_FINASSET_YOY',
 'APPOINT_FVTPL_FINLIAB_YOY',
 'ASSET_BALANCE_YOY',
 'ASSET_OTHER_YOY',
 'ASSIGN_CASH_DIVIDEND_YOY',
 'AVAILABLE_SALE_FINASSET_YOY',
 'BOND_PAYABLE_YOY',
 'BORROW_FUND_YOY',
 'BUY_RESALE_FINASSET_YOY',
 'CAPITAL_RESERVE_YOY',
 'CIP_YOY',
 'CONSUMPTIVE_BIOLOGICAL_ASSET_YOY',
 'CONTRACT_ASSET_YOY',
 'CONTRACT_LIAB_YOY',
 'CONVERT_DIFF_YOY',
 'CREDITOR_INVEST_YOY',
 'CURRENT_ASSET_BALANCE_YOY',
 'CURRENT_ASSET_OTHER_YOY',
 'CURRENT_LIAB_BALANCE_YOY',
 'CURRENT_LIAB_OTHER_YOY',
 'DEFER_INCOME_1YEAR_YOY',
 'DEFER_INCOME_YOY',
 'DEFER_TAX_ASSET_YOY',
 'DEFER_TAX_LIAB_YOY',
 'DERIVE_FINASSET_YOY',
 'DERIVE_FINLIAB_YOY',
 'DEVELOP_EXPENSE_YOY',
 'DIV_HOLDSALE_ASSET_YOY',
 'DIV_HOLDSALE_LIAB_YOY',
 'DIVIDEND_PAYABLE_YOY',
 'DIVIDEND_RECE_YOY',
 'EQUITY_BALANCE_YOY',
 'EQUITY_OTHER_YOY',
 'EXPORT_REFUND_RECE_YOY',
 'FEE_COMMISSION_PAYABLE_YOY',
 'FIN_FUND_YOY',
 'FINANCE_RECE_YOY',
 'FIXED_ASSET_DISPOSAL_YOY',
 'FIXED_ASSET_YOY',
 'FVTOCI_FINASSET_YOY',
 'FVTOCI_NCFINASSET_YOY',
 'FVTPL_FINASSET_YOY',
 'FVTPL_FINLIAB_YOY',
 'GENERAL_RISK_RESERVE_YOY',
 'GOODWILL_YOY',
 'HOLD_MATURITY_INVEST_YOY',
 'HOLDSALE_ASSET_YOY',
 'HOLDSALE_LIAB_YOY',
 'INSURANCE_CONTRACT_RESERVE_YOY',
 'INTANGIBLE_ASSET_YOY',
 'INTEREST_PAYABLE_YOY',
 'INTEREST_RECE_YOY',
 'INTERNAL_PAYABLE_YOY',
 'INTERNAL_RECE_YOY',
 'INVENTORY_YOY',
 'INVEST_REALESTATE_YOY',
 'LEASE_LIAB_YOY',
 'LEND_FUND_YOY',
 'LIAB_BALANCE_YOY',
 'LIAB_EQUITY_BALANCE_YOY',
 'LIAB_EQUITY_OTHER_YOY',
 'LIAB_OTHER_YOY',
 'LOAN_ADVANCE_YOY',
 'LOAN_PBC_YOY',
 'LONG_EQUITY_INVEST_YOY',
 'LONG_LOAN_YOY',
 'LONG_PAYABLE_YOY',
 'LONG_PREPAID_EXPENSE_YOY',
 'LONG_RECE_YOY',
 'LONG_STAFFSALARY_PAYABLE_YOY',
 'MINORITY_EQUITY_YOY',
 'MONETARYFUNDS_YOY',
 'NONCURRENT_ASSET_1YEAR_YOY',
 'NONCURRENT_ASSET_BALANCE_YOY',
 'NONCURRENT_ASSET_OTHER_YOY',
 'NONCURRENT_LIAB_1YEAR_YOY',
 'NONCURRENT_LIAB_BALANCE_YOY',
 'NONCURRENT_LIAB_OTHER_YOY',
 'NOTE_ACCOUNTS_PAYABLE_YOY',
 'NOTE_ACCOUNTS_RECE_YOY',
 'NOTE_PAYABLE_YOY',
 'NOTE_RECE_YOY',
 'OIL_GAS_ASSET_YOY',
 'OTHER_COMPRE_INCOME_YOY',
 'OTHER_CREDITOR_INVEST_YOY',
 'OTHER_CURRENT_ASSET_YOY',
 'OTHER_CURRENT_LIAB_YOY',
 'OTHER_EQUITY_INVEST_YOY',
 'OTHER_EQUITY_OTHER_YOY',
 'OTHER_EQUITY_TOOL_YOY',
 'OTHER_NONCURRENT_ASSET_YOY',
 'OTHER_NONCURRENT_FINASSET_YOY',
 'OTHER_NONCURRENT_LIAB_YOY',
 'OTHER_PAYABLE_YOY',
 'OTHER_RECE_YOY',
 'PARENT_EQUITY_BALANCE_YOY',
 'PARENT_EQUITY_OTHER_YOY',
 'PERPETUAL_BOND_PAYBALE_YOY',
 'PERPETUAL_BOND_YOY',
 'PREDICT_CURRENT_LIAB_YOY',
 'PREDICT_LIAB_YOY',
 'PREFERRED_SHARES_PAYBALE_YOY',
 'PREFERRED_SHARES_YOY',
 'PREMIUM_RECE_YOY',
 'PREPAYMENT_YOY',
 'PRODUCTIVE_BIOLOGY_ASSET_YOY',
 'PROJECT_MATERIAL_YOY',
 'RC_RESERVE_RECE_YOY',
 'REINSURE_PAYABLE_YOY',
 'REINSURE_RECE_YOY',
 'SELL_REPO_FINASSET_YOY',
 'SETTLE_EXCESS_RESERVE_YOY',
 'SHARE_CAPITAL_YOY',
 'SHORT_BOND_PAYABLE_YOY',
 'SHORT_FIN_PAYABLE_YOY',
 'SHORT_LOAN_YOY',
 'SPECIAL_PAYABLE_YOY',
 'SPECIAL_RESERVE_YOY',
 'STAFF_SALARY_PAYABLE_YOY',
 'SUBSIDY_RECE_YOY',
 'SURPLUS_RESERVE_YOY',
 'TAX_PAYABLE_YOY',
 'TOTAL_ASSETS_YOY',
 'TOTAL_CURRENT_ASSETS_YOY',
 'TOTAL_CURRENT_LIAB_YOY',
 'TOTAL_EQUITY_YOY',
 'TOTAL_LIAB_EQUITY_YOY',
 'TOTAL_LIABILITIES_YOY',
 'TOTAL_NONCURRENT_ASSETS_YOY',
 'TOTAL_NONCURRENT_LIAB_YOY',
 'TOTAL_OTHER_PAYABLE_YOY',
 'TOTAL_OTHER_RECE_YOY',
 'TOTAL_PARENT_EQUITY_YOY',
 'TRADE_FINASSET_NOTFVTPL_YOY',
 'TRADE_FINASSET_YOY',
 'TRADE_FINLIAB_NOTFVTPL_YOY',
 'TRADE_FINLIAB_YOY',
 'TREASURY_SHARES_YOY',
 'UNASSIGN_RPOFIT_YOY',
 'UNCONFIRM_INVEST_LOSS_YOY',
 'USERIGHT_ASSET_YOY',
 'OPINION_TYPE',
 'OSOPINION_TYPE',
 'LISTING_STATE']

In [84]:
df = ak.stock_history_dividend_detail(symbol="603636") # indicator="分红"

In [85]:
df

         公告日期  送股  转增    派息  进度       除权除息日       股权登记日 红股上市日
0  2022-06-10   0   0  0.85  实施  2022-06-16  2022-06-15   NaT
1  2021-07-05   0   0  1.20  实施  2021-07-09  2021-07-08   NaT
2  2020-06-13   0   0  1.60  实施  2020-06-19  2020-06-18   NaT
3  2019-05-13   0   0  1.20  实施  2019-05-17  2019-05-16   NaT
4  2018-05-03   0   0  2.00  实施  2018-05-10  2018-05-09   NaT
5  2017-03-30   0  30  1.60  实施  2017-04-07  2017-04-06   NaT
6  2016-06-28   0   0  1.90  实施  2016-07-05  2016-07-04   NaT
7  2015-08-04   0   0  1.80  实施  2015-08-10  2015-08-07   NaT