In [1]:
import baostock as bs
import pandas as pd

In [13]:
#### 登陆系统 ####
lg = bs.login()
# 显示登陆返回信息
print('login respond error_code:'+lg.error_code)
print('login respond  error_msg:'+lg.error_msg)

#### 获取沪深A股历史K线数据 ####
# 详细指标参数，参见“历史行情指标参数”章节；“分钟线”参数与“日线”参数不同。“分钟线”不包含指数。
# 分钟线指标：date,time,code,open,high,low,close,volume,amount,adjustflag
# 周月线指标：date,code,open,high,low,close,volume,amount,adjustflag,turn,pctChg
# sh.600000
rs = bs.query_history_k_data_plus("sh.603636", "date,time,code,open,high,low,close,volume,amount,adjustflag",
    start_date='2012-07-01', end_date='2021-11-02',
    frequency="5") #, adjustflag="3")
print('query_history_k_data_plus respond error_code:'+rs.error_code)
print('query_history_k_data_plus respond  error_msg:'+rs.error_msg)

#### 打印结果集 ####
data_list = []
while (rs.error_code == '0') & rs.next():
    # 获取一条记录，将记录合并在一起
    data_list.append(rs.get_row_data())
result = pd.DataFrame(data_list, columns=rs.fields)

#### 结果集输出到csv文件 ####   
# result.to_csv("D:\\history_A_stock_k_data.csv", index=False)
print(result)

#### 登出系统 ####
bs.logout()

login success!
login respond error_code:0
login respond  error_msg:success
query_history_k_data_plus respond error_code:0
query_history_k_data_plus respond  error_msg:success
             date               time       code     open     high      low  \
0      2014-12-30  20141230093500000  sh.603636  17.9400  21.5300  17.9400
1      2014-12-30  20141230094000000  sh.603636  21.5300  21.5300  21.5300
2      2014-12-30  20141230094500000  sh.603636  21.5300  21.5300  21.5300
3      2014-12-30  20141230095000000  sh.603636  21.5300  21.5300  21.5300
4      2014-12-30  20141230095500000  sh.603636  21.5300  21.5300  21.5300
...           ...                ...        ...      ...      ...      ...
76267  2021-11-01  20211101144000000  sh.603636   8.0100   8.0100   8.0000
76268  2021-11-01  20211101144500000  sh.603636   8.0100   8.0200   8.0000
76269  2021-11-01  20211101145000000  sh.603636   8.0200   8.0200   8.0000
76270  2021-11-01  20211101145500000  sh.603636   8.0100   8.0300   8.0100
76271  2021-11-01  20211101150000000  sh.603636   8.0200   8.0500   8.0200

         close  volume       amount adjustflag
0      21.5300    1200   25118.0000          3
1      21.5300       0       0.0000          3
2      21.5300       0       0.0000          3
3      21.5300       0       0.0000          3
4      21.5300       0       0.0000          3
...        ...     ...          ...        ...
76267   8.0000   32100  257047.0000          3
76268   8.0100   21300  170720.0000          3
76269   8.0100   39000  312404.0000          3
76270   8.0200  105500  846450.0000          3
76271   8.0300   83500  670733.0000          3

[76272 rows x 10 columns]
logout success!

In [6]:
result

,date,time,code,open,high,low,close,volume,amount,adjustflag
0,2014-12-30,20141230093500000,sh.603636,17.9400,21.5300,17.9400,21.5300,1200,25118.0000,3
1,2014-12-30,20141230094000000,sh.603636,21.5300,21.5300,21.5300,21.5300,0,0.0000,3
2,2014-12-30,20141230094500000,sh.603636,21.5300,21.5300,21.5300,21.5300,0,0.0000,3
3,2014-12-30,20141230095000000,sh.603636,21.5300,21.5300,21.5300,21.5300,0,0.0000,3
4,2014-12-30,20141230095500000,sh.603636,21.5300,21.5300,21.5300,21.5300,0,0.0000,3
...,...,...,...,...,...,...,...,...,...,...
73435,2021-07-30,20210730144000000,sh.603636,9.0500,9.0500,9.0400,9.0400,35100,317519.0000,3
73436,2021-07-30,20210730144500000,sh.603636,9.0500,9.0500,9.0300,9.0400,61200,553468.5600,3
73437,2021-07-30,20210730145000000,sh.603636,9.0400,9.0600,9.0400,9.0500,76100,688606.0000,3
73438,2021-07-30,20210730145500000,sh.603636,9.0500,9.0600,9.0300,9.0300,77500,701419.0000,3
73439,2021-07-30,20210730150000000,sh.603636,9.0400,9.0400,9.0300,9.0400,25820,233384.8000,3

In [15]:
result[result['date'] == '2021-10-28']

,date,time,code,open,high,low,close,volume,amount,adjustflag
76128,2021-10-28,20211028093500000,sh.603636,8.1300,8.1700,8.1200,8.1400,84800,689967.0000,3
76129,2021-10-28,20211028094000000,sh.603636,8.1400,8.1800,8.1400,8.1700,24400,199005.0000,3
76130,2021-10-28,20211028094500000,sh.603636,8.1600,8.1600,8.1200,8.1200,83300,678154.0000,3
76131,2021-10-28,20211028095000000,sh.603636,8.1200,8.1400,8.1200,8.1400,27600,224473.0000,3
76132,2021-10-28,20211028095500000,sh.603636,8.1400,8.1400,8.1300,8.1300,19900,161821.0000,3
76133,2021-10-28,20211028100000000,sh.603636,8.1300,8.1300,8.1100,8.1100,46500,377561.0000,3
76134,2021-10-28,20211028100500000,sh.603636,8.1100,8.1200,8.0700,8.0800,71700,580460.0000,3
76135,2021-10-28,20211028101000000,sh.603636,8.0800,8.0900,8.0200,8.0400,117300,944022.0000,3
76136,2021-10-28,20211028101500000,sh.603636,8.0400,8.0500,8.0100,8.0400,205880,1651626.0000,3
76137,2021-10-28,20211028102000000,sh.603636,8.0400,8.0800,8.0400,8.0400,40800,328585.0000,3
76138,2021-10-28,20211028102500000,sh.603636,8.0400,8.0600,8.0400,8.0400,38600,310489.0000,3
76139,2021-10-28,20211028103000000,sh.603636,8.0400,8.0600,8.0400,8.0600,20600,165747.0000,3
76140,2021-10-28,20211028103500000,sh.603636,8.0600,8.0700,8.0500,8.0600,19498,157208.0000,3
76141,2021-10-28,20211028104000000,sh.603636,8.0600,8.0600,8.0500,8.0500,43200,347812.0000,3
76142,2021-10-28,20211028104500000,sh.603636,8.0500,8.0600,8.0500,8.0500,6100,49108.0000,3
76143,2021-10-28,20211028105000000,sh.603636,8.0500,8.0800,8.0500,8.0600,17200,138699.0000,3
76144,2021-10-28,20211028105500000,sh.603636,8.0600,8.0700,8.0600,8.0700,25360,204466.0000,3
76145,2021-10-28,20211028110000000,sh.603636,8.0700,8.0900,8.0700,8.0900,17000,137427.0000,3
76146,2021-10-28,20211028110500000,sh.603636,8.0900,8.1000,8.0900,8.1000,11700,94767.0000,3
76147,2021-10-28,20211028111000000,sh.603636,8.1000,8.1100,8.1000,8.1100,14700,119212.0000,3
76148,2021-10-28,20211028111500000,sh.603636,8.1100,8.1200,8.1100,8.1100,13700,111110.0000,3
76149,2021-10-28,20211028112000000,sh.603636,8.1100,8.1200,8.1000,8.1200,10600,85868.0000,3
76150,2021-10-28,20211028112500000,sh.603636,8.1200,8.1200,8.1000,8.1000,11200,90745.0000,3
76151,2021-10-28,20211028113000000,sh.603636,8.1000,8.1200,8.1000,8.1200,12500,101463.0000,3
76152,2021-10-28,20211028130500000,sh.603636,8.1200,8.1300,8.1200,8.1300,24500,199060.0000,3
76153,2021-10-28,20211028131000000,sh.603636,8.1300,8.1300,8.1200,8.1300,8400,68268.0000,3
76154,2021-10-28,20211028131500000,sh.603636,8.1300,8.1300,8.1200,8.1300,5400,43901.0000,3
76155,2021-10-28,20211028132000000,sh.603636,8.1300,8.1400,8.1200,8.1400,7600,61817.0000,3
76156,2021-10-28,20211028132500000,sh.603636,8.1400,8.1400,8.1200,8.1200,53300,432922.0000,3
76157,2021-10-28,20211028133000000,sh.603636,8.1200,8.1300,8.1200,8.1200,17100,138854.0000,3
76158,2021-10-28,20211028133500000,sh.603636,8.1200,8.1400,8.1200,8.1400,29600,240718.0000,3
76159,2021-10-28,20211028134000000,sh.603636,8.1400,8.1700,8.1400,8.1600,77145,629511.0000,3
76160,2021-10-28,20211028134500000,sh.603636,8.1600,8.2400,8.1600,8.2400,183998,1509977.0000,3
76161,2021-10-28,20211028135000000,sh.603636,8.2500,8.3000,8.2200,8.2600,233700,1932651.0000,3
76162,2021-10-28,20211028135500000,sh.603636,8.2600,8.2600,8.2100,8.2400,56400,464890.0000,3
76163,2021-10-28,20211028140000000,sh.603636,8.2400,8.2700,8.2100,8.2400,86800,716358.0000,3
76164,2021-10-28,20211028140500000,sh.603636,8.2400,8.2600,8.2400,8.2600,4600,37992.0000,3
76165,2021-10-28,20211028141000000,sh.603636,8.2600,8.2600,8.2200,8.2300,40300,332016.0000,3
76166,2021-10-28,20211028141500000,sh.603636,8.2300,8.2400,8.2200,8.2400,12900,106287.0000,3
76167,2021-10-28,20211028142000000,sh.603636,8.2400,8.2400,8.2300,8.2300,8800,72442.0000,3
76168,2021-10-28,20211028142500000,sh.603636,8.2300,8.2300,8.2000,8.2100,31500,258884.0000,3
76169,2021-10-28,20211028143000000,sh.603636,8.2100,8.2200,8.2100,8.2200,9700,79662.0000,3
76170,2021-10-28,20211028143500000,sh.603636,8.2100,8.2100,8.2000,8.2100,51600,423292.0000,3
76171,2021-10-28,20211028144000000,sh.603636,8.2100,8.2100,8.1900,8.2000,22300,182907.0000,3
76172,2021-10-28,20211028144500000,sh.603636,8.2000,8.2000,8.1700,8.1700,106400,870982.0000,3
76173,2021-10-28,20211028145000000,sh.603636,8.1800,8.1800,8.1700,8.1700,40100,328007.0000,3
76174,2021-10-28,20211028145500000,sh.603636,8.1700,8.1800,8.1600,8.1600,70400,575157.0000,3
76175,2021-10-28,20211028150000000,sh.603636,8.1700,8.1800,8.1700,8.1800,39117,319839.0000,3

In [16]:
df.loc['2021-10-28']

                                open  close  high   low    volume     amount
date       datetime
2021-10-28 2021-10-28 09:35:00  8.13   8.15  8.17  8.12   84500.0   687525.0
           2021-10-28 09:40:00  8.14   8.17  8.18  8.14   24700.0   201447.0
           2021-10-28 09:45:00  8.16   8.12  8.16  8.12   83300.0   678154.0
           2021-10-28 09:50:00  8.13   8.14  8.14  8.13   27600.0   224473.0
           2021-10-28 09:55:00  8.14   8.13  8.14  8.13   19900.0   161821.0
           2021-10-28 10:00:00  8.13   8.11  8.13  8.11   46500.0   377561.0
           2021-10-28 10:05:00  8.11   8.08  8.12  8.07   71700.0   580460.0
           2021-10-28 10:10:00  8.08   8.03  8.09  8.02  114000.0   917520.0
           2021-10-28 10:15:00  8.04   8.04  8.05  8.01  208600.0  1673304.0
           2021-10-28 10:20:00  8.04   8.04  8.08  8.04   41400.0   333409.0
           2021-10-28 10:25:00  8.04   8.04  8.06  8.04   38600.0   310489.0
           2021-10-28 10:30:00  8.04   8.06  8.06  8.04   20600.0   165747.0
           2021-10-28 10:35:00  8.06   8.06  8.07  8.05   19500.0   157208.0
           2021-10-28 10:40:00  8.06   8.05  8.06  8.05   43200.0   347812.0
           2021-10-28 10:45:00  8.05   8.05  8.06  8.05    6100.0    49108.0
           2021-10-28 10:50:00  8.06   8.06  8.08  8.05   17200.0   138699.0
           2021-10-28 10:55:00  8.06   8.07  8.07  8.06   25300.0   204466.0
           2021-10-28 11:00:00  8.07   8.09  8.09  8.07   16000.0   129337.0
           2021-10-28 11:05:00  8.09   8.10  8.10  8.09   12700.0   102857.0
           2021-10-28 11:10:00  8.10   8.11  8.11  8.10   14700.0   119212.0
           2021-10-28 11:15:00  8.12   8.11  8.12  8.11   13700.0   111110.0
           2021-10-28 11:20:00  8.11   8.12  8.12  8.10   10600.0    85868.0
           2021-10-28 11:25:00  8.12   8.10  8.12  8.10   11200.0    90745.0
           2021-10-28 11:30:00  8.11   8.12  8.12  8.11   12500.0   101463.0
           2021-10-28 13:05:00  8.12   8.13  8.13  8.12   24500.0   199060.0
           2021-10-28 13:10:00  8.12   8.13  8.13  8.12    8400.0    68268.0
           2021-10-28 13:15:00  8.13   8.13  8.13  8.12    5400.0    43901.0
           2021-10-28 13:20:00  8.13   8.14  8.14  8.12    7600.0    61817.0
           2021-10-28 13:25:00  8.12   8.12  8.14  8.12   53300.0   432922.0
           2021-10-28 13:30:00  8.12   8.12  8.13  8.12   17100.0   138854.0
           2021-10-28 13:35:00  8.12   8.14  8.14  8.12   29600.0   240718.0
           2021-10-28 13:40:00  8.14   8.16  8.17  8.14   77200.0   629511.0
           2021-10-28 13:45:00  8.16   8.24  8.24  8.16  184000.0  1509977.0
           2021-10-28 13:50:00  8.25   8.26  8.30  8.22  233700.0  1932651.0
           2021-10-28 13:55:00  8.26   8.24  8.26  8.21   56400.0   464890.0
           2021-10-28 14:00:00  8.24   8.24  8.27  8.21   86800.0   716358.0
           2021-10-28 14:05:00  8.24   8.26  8.26  8.24    4600.0    37992.0
           2021-10-28 14:10:00  8.25   8.23  8.25  8.22   40300.0   332016.0
           2021-10-28 14:15:00  8.24   8.24  8.24  8.22   12900.0   106287.0
           2021-10-28 14:20:00  8.24   8.23  8.24  8.23    8800.0    72442.0
           2021-10-28 14:25:00  8.22   8.21  8.23  8.20   31500.0   258884.0
           2021-10-28 14:30:00  8.21   8.22  8.22  8.21    9700.0    79662.0
           2021-10-28 14:35:00  8.21   8.21  8.21  8.20   51600.0   423292.0
           2021-10-28 14:40:00  8.21   8.20  8.21  8.19   22300.0   182907.0
           2021-10-28 14:45:00  8.20   8.17  8.20  8.17  106400.0   870982.0
           2021-10-28 14:50:00  8.18   8.17  8.18  8.17   40100.0   328006.0
           2021-10-28 14:55:00  8.17   8.16  8.18  8.16   70400.0   575158.0
           2021-10-28 15:00:00  8.17   8.18  8.18  8.17   39100.0   319838.0

In [8]:
from lutils.stock import LTdxHq

In [9]:
ltdxhq = LTdxHq()

In [10]:
df = ltdxhq.get_k_data_5min('603636', qfq=False)